    
---
- hosts: test
  become: True
  become_method: sudo
  become_user: root
  vars:
    ansible_become_pass: amen
  tasks:
    - script: ./solr.sh
    - name: copy fiies
      copy:
         src: solrconfig.xml
         dest: /var/solr/data/ckan/conf
         force: yes
    - name: copy fles 2
      copy:
         src: schema.xml
         dest: /var/solr/data/ckan/conf
         force: yes
    - script: ./ckan.sh
  
